### ISSUE TITLE
Memory management chaos issues in RT - PPP

### ISSUE THREAD

**Issue by LJC8848** [GeoscienceAustralia/ginan#106]
PEA starting... (  from )

Checking configuration file rt_ppp_example.yaml
Loading configuration from file rt_ppp_example.yaml

===============================
Configuration Summary...
===============================
Inputs:
	snx_files:                       ./products/tables/igs_satellite_metadata_2203_plus.snx 
	atx_files:                       ./products/tables/igs20.atx 
	igrf_files:                      ./products/tables/igrf13coeffs.txt 
	ocean_tide_loading_blq_files:    ./products/tables/OLOAD_GO.BLQ 
	atmos_tide_loading_blq_files:    ./products/tables/ALOAD_GO.BLQ 
	ocean_pole_tide_loading_files:   ./products/tables/opoleloadcoefcmcor.txt 
	erp_files:                       ./products/tables/finals.data.iau2000.txt 
	egm_files:                       ./products/tables/EGM2008.gfc 
	planetary_ephemeris_files:       ./products/tables/DE436.1950.2050 
	ocean_tide_potential_files:      ./products/tables/fes2014b_Cnm-Snm.dat 
	gpt2grid_files:                  ./products/tables/gpt_25.grd 
	rtcm_inputs:                     https://206258902@qq.com:5554271127.Zz@ntrip.data.gnss.ga.gov.au/BCEP00BKG0 https://206258902@qq.com:5554271127.Zz@ntrip.data.gnss.ga.gov.au/SSRA00BKG0 
	rtcm_inputs:                     https://206258902@qq.com:5554271127.Zz@ntrip.data.gnss.ga.gov.au/STR200AUS0 

Outputs:
	trace level:                   4
	receiver trace filename:       ./outputs/rt_ppp_example/<RECEIVER>_rt_ppp_example_<YYYY><DDD><HH>.TRACE
	network trace filename:        ./outputs/rt_ppp_example/<RECEIVER>_rt_ppp_example_<YYYY><DDD><HH>.TRACE
	gpx filename:                  ./outputs/rt_ppp_example/rt_ppp_example_<RECEIVER>_<YYYY><DDD><HH>.GPX

Process Modes:
	Preprocessor:        1
	SPP                  1
	PPP:                 1
	Minimum Constraints: 0
	Ionospheric:         0
	RTS Smoothing:       0

Systems:
	GPS:     1
	GLONASS: 0
	GALILEO: 0
	BEIDOU:  0
	QZSS:    0
	LEO:     0

Epochs:
	epoch_interval: 20

===============================
...End Configuration Summary
===============================

Compilation details:
====================
Ginan branch:     
Ginan version:    
Commit date:      
Operating system: "Ubuntu 22.04.4 LTS"
Compiler version: GNU 11.4.0
Boost version:    1.74.0
Eigen version:    3.4.0
Mongocxx version: 3.7.0

Runtime details:
================
Logging at trace level4
Threading with max 16 eigen threads
Threading with max 16 omp threads

Mongo connecting to database @ mongodb://localhost:27017
Loading ATX file ./products/tables/igs20.atx
Loading ERP file ./products/tables/finals.data.iau2000.txt
Loading IGRF file ./products/tables/igrf13coeffs.txt
Loading SNX file ./products/tables/igs_satellite_metadata_2203_plus.snx
Loading GPT file ./products/tables/gpt_25.grd
Loading Ocean Pole Tide file ./products/tables/opoleloadcoefcmcor.txt
Loading EGM file ./products/tables/EGM2008.gfc
Loading Tide file ./products/tables/fes2014b_Cnm-Snm.dat
Loading planetary ephemeris file ./products/tables/DE436.1950.2050
Initialising station STR2
Mongo connecting to database : rt_ppp_example @ mongodb://localhost:27017
Mongo connected  to database : rt_ppp_example

Starting to process epochs...

Starting epoch #1
Synced 0 receivers...
Processed epoch #1 - GPS time: 2331 362020 - 2024-Sep-12 04:33:40 (took 00:00:00.00)

Starting epoch #2
Synced 1 receivers...
 ------- PREPROCESSING STATIONS       --------
double free or corruption (out)
已中止 (核心已转储)

**Comment by seballgeyer** [comment]
Hello

Thank you for reporting this issue and providing the log. We believe this problem is related to a bug in the code where an element was being removed without checking if it existed first. This seems to be platform-specific, likely related to Ubuntu 22 or the version of the GNU compiler you're using. We've already addressed this issue, and the fix will be included in the next automated push to the develop-weekly branch later today (the weekly update is every Friday evening at about 5pm  Canberra time).

Additionally, for future issues, it would be very helpful if you could use the issue template when raising a report. This ensures we have all the necessary information (e.g., exact versions, configurations) right from the start, which can speed up diagnosis and resolution.

Thanks for your patience, and let us know if you encounter any further problems!

Best regards
