### ISSUE TITLE
PPP example does not work well

### ISSUE THREAD

**Issue by wangstrong1996** [GeoscienceAustralia/ginan#11]
Hi Ginan Team,

Recently, I have tried ginan with the provided example data. However, it seems the PPP results are not very good. Here are the results:

![388777f558251a30b35b106a963a943](https://user-images.githubusercontent.com/53374617/167364128-3456851a-bc22-4ed3-a182-4c27617624a4.jpg)

Should it be like this? 

Best,
Shizhuang Wang

**Comment by smcclusky** [comment]
Hi Shizuang,
Can you please post the Ginan config file you used or the example number if you didn't change the config and we will run it here in our development environment server.
Thanks

**Comment by wangstrong1996** [comment]
Dear Team,

Thanks for your response. Here is the YAML file we use. We only change the file path in this configuration file.
 
Thank you for your help and for this excellent open-source software.

Best,
Shizhuang

[Uploading ex14_pea_pp_user_gnss_ar_a5.zip…]()

**Comment by JohnDonovanGA** [comment]
link is just to this document. closing.
