### ISSUE TITLE
code2Freq BDS B2a+B2b 8Z might this be 8X?

### ISSUE THREAD

**Issue by ourairquality** [GeoscienceAustralia/ginan#121]
**Describe the bug**

Looking at the code for code2Freq in constants.cpp, and BDS B2a+B2b lists L8D L8P L8Z, but looking at the RINEX 4.01 spec this appears to be listed as L8D L8P and L8X (not L8Z), and might this be a typo?

**Comment by seballgeyer** [comment]
Thank you for reporting this. 

Effectively it is a typo in the code. We did fix it in our codebase. It will be updated in github later today in the `develop-weekly` branch.

Best regards,
Sébastien
