### ISSUE TITLE
Some problem of download the example data

### ISSUE THREAD

**Issue by k9891** [GeoscienceAustralia/ginan#14]
Hi Ginan Team. Recently, I try to use ginan to some researchs. But, I can't download the example data. The "download_examples.py" returns error of "urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>", and the link you provided also returns "ERR_CONNECTION_TIMED_OUT" . Is there any other way to download the data? Thanks.

**Comment by k9891** [comment]
Hi, bmatv. I try it, but I can't  download any of the top two files manually. I think it's problem of the network. If you are convenient, would you mind sending the example data to my email: kun.c@njnu.edu.cn ? Thanks.

**Comment by canvaskan** [comment]
Hi, @k9891 . Thanks for your issue. I encountered same problem with download_example.py, but I managed to dowload data.tar.bz2 and products.tar.bz2 by the link above. I can send you a copy.

**Comment by bmatv** [comment]
Hi @k9891 and @canvaskan,
I've published a set of auxiliary products/solutions on github (relevant Ginan v1.4-beta release), this way @k9891's access can be guaranteed. Just clone the repository on your disk and copy over the files to the `ginan/examples`. Here is a link: https://github.com/bmatv/ginan_aux

> Hi, @k9891 . Thanks for your issue. I encountered same problem with download_example.py, but I managed to dowload data.tar.bz2 and products.tar.bz2 by the link above. I can send you a copy.

Thank you for your help, @canvaskan

**Comment by k9891** [comment]
> Hi, @k9891 . Thanks for your issue. I encountered same problem with download_example.py, but I managed to dowload data.tar.bz2 and products.tar.bz2 by the link above. I can send you a copy.

Hi, canvaskan. I have downloaded the sample data, thank you very much.

**Comment by k9891** [comment]
Hi, Ginan team. Thank you very much!




ck961030
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GeoscienceAustralia/ginan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月7日(星期四) 下午5:49
***@***.***&gt;;
抄送:&nbsp;"幽灵@***@***.******@***.***&gt;;
主题:&nbsp;Re: [GeoscienceAustralia/ginan] Some problem of download the example data (Issue #14)





 
Hi @k9891 and @canvaskan,
 I've published a set of auxiliary products/solutions on github (relevant Ginan v1.4-beta release), this way @k9891's access can be guaranteed. Just clone the repository on your disk and copy over the files to the ginan/examples. Here is a link: https://github.com/bmatv/ginan_aux
  
Hi, @k9891 . Thanks for your issue. I encountered same problem with download_example.py, but I managed to dowload data.tar.bz2 and products.tar.bz2 by the link above. I can send you a copy.
  
Thank you for your help, @canvaskan

**Comment by LJC8848** [comment]
Hi, @k9891 .I encountered same problem with download_example.py,would you mind sending the example data to my email: 206258902@qq.com ? Thanks.
