### ISSUE TITLE
ionmodel part 

### ISSUE THREAD

**Issue by DoubleString** [GeoscienceAustralia/ginan#15]
Hi, ginan team, recently we tried to adopt the coefficient generated function `configure_iono_model_sphcap` provided in `ionosphericalcaps.cpp  ` for ionosphere model, but something went wrong when i called `configure_iono_model_sphcap` and we got a nan output after  `legendre_function` . The while loop can not be broken. The `latc` `lonc` `latw` and `lonw` are set as (23,113,40,40). Is this caused by the code or the inputs? We sincerely look forward to your replys. Further we are confused by the condition code `if((p1 * p1) < 0) at line 367 and 399`, since it will be never fulfilled.

**Comment by KAHarima** [comment]
Hi DoubleString,
Unfortunately the B-splines and Spherical Harmonic Caps Ionosphere models are not supported at the moment

**Comment by KAHarima** [comment]
If you are interested in testing the function alone, you may want to use radian values for latc lonc latw and lonw

**Comment by DoubleString** [comment]
I understand, many thanks!

**Comment by KAHarima** [comment]
The expression (p1*p1)<0 is a bug (typo), it should be p1*p2<0. Thank you very much for helping us find it. Unfortunately this model is not maintained, we will add a comment as a warning.

**Comment by JohnDonovanGA** [comment]
Issue closed
