### ISSUE TITLE
Can Ginan do LEO POD?

### ISSUE THREAD

**Issue by jianyaoucar** [GeoscienceAustralia/ginan#21]
Dear Ginan Team,

Is it possible for Ginan to do the reduced-dynamic low-Earth-orbit satellite orbit determination? I'm thinking that I can do PPP to get a rough estimate of LEO positions using PEA and then do LEO orbit fitting using POD, and then use the LEO orbit fitting result as the input for a second run of PPP, so on and so forth until the residuals become small. However, there seems no way to provide pre-known positions of a kinematic receiver (for my situation, that is the LEO orbit fitting coordinates) as the input of PPP? If this is the case, each run of PPP would give the same LEO POD result and thus I cannot achieve the reduced-dynamic LEO orbit determination using Ginan, am I right?
Thanks very much and waiting for your reply :)

Jian Yao from UCAR

**Comment by JohnDonovanGA** [comment]
Hi Jian, LEO is on our radar but not due for release until next year sometime. We do have someone working on it.

**Comment by jianyaoucar** [comment]
Hi John,

It seems that Rupert said that GINAN 2.0 Beta has the precise orbit
determination capability (see the screenshot of his email). So this POD
capability only applies to MEO satellites, not LEOs?

Thanks,

Jian

**Comment by seballgeyer** [comment]
Hi Jian,

Here is some additional information that should address your query:

1. One of the major changes in Ginan from version 1 to version 2 is the integration of the POD (Fortran) module into the PEA (C++) source code.

2. Currently, this integration is complete and replicates the functionality of the Fortran version of the POD. As a result, orbit determination of the transmitter is now available.

3. However, to have full capability for LEO satellites, there are some missing parts that we are actively working on:

  a. Orbit determination as a GNSS receiver, including kinematic, dynamic, and reduced dynamic modes.
  b. Incorporating additional acceleration in the forward modeling of orbits. These accelerations are negligible at GNSS altitudes but necessary at LEO altitudes.

We are currently focusing on these aspects and aim to release these features by early next year.

I hope this answers your question. If you have any further inquiries, please let us know.

Sebastien
