### ISSUE TITLE
i can't  download a ready-to-run Ginan environment using docker,beacuse the download speed is very slow and even stops

### ISSUE THREAD

**Issue by lk4564512486** [GeoscienceAustralia/ginan#23]
i can't  download a ready-to-run Ginan environment using docker,beacuse the download speed is very slow and even stops.
this command:
docker run -it -v /data:/data gnssanalysis/ginan:v1.5.1 bash

**Comment by zhuhangfei** [comment]
挂镜像

**Comment by JohnDonovanGA** [comment]
wifi issue? closing

**Comment by zhuhangfei** [comment]
在 2023-05-30 11:58:06，"JohnDonovanGA" ***@***.***> 写道：

wifi issue? closing
