### ISSUE TITLE
Standalone installation for PEA

### ISSUE THREAD

**Issue by hsergi** [GeoscienceAustralia/ginan#28]
Is it possible to install the pea only? Or is the distribution thought to be complete: pod+pea?

**Comment by smcclusky** [comment]
The Ginan distribution contains the source code for both the PEA and POD. 
However, as per the Readme, after the (cmake ..) step you can choose to make all the executables targets:

make -j2

Or make PEA and POD executables targets separately.

make pea -j2

make pod -j2

**Comment by hsergi** [comment]
Thanks for the reminder.
