### ISSUE TITLE
Installation Challenge — MongocxxConfig

### ISSUE THREAD

**Issue by Waley04** [GeoscienceAustralia/ginan#35]
Greetings Developers, 

I am very impressed with the level of detail and thought that has gone into its Ginan Software.

However, I am writing to report an issue that we have encountered during the installation process. I have followed the installation instructions provided, but I am unable to complete the installation successfully. Here is the error message as shown in the screenshot.

![image](https://github.com/GeoscienceAustralia/ginan/assets/101952777/1dbffaff-70d4-4d74-9f3d-395b21fb787b)

1. System: Linux 
2. Issue: CMake Error at CMakeLists.txt:154 (find_package)

I have tried to troubleshoot the issue on my own (by following similar in this repository), but I have been unable to find a solution. 

I would appreciate your assistance in resolving this matter as soon as possible, as I am eager to continue with the installation.

Regards,

Waley.

**Comment by JohnDonovanGA** [comment]
Hi Waley,
it looks like you are trying to install Ginan on WSL2 (Windows service for Linux). Is this correct? Did you actually manage to get mongoCXX installed? You may need to tinker with the mongocxxConfig.cmake file if it did install. Just trying to replicate your exact environment.
Thanks
John

**Comment by gnssLa** [comment]
Hi John,

Thank you for your email. Yes, I am on WSL, and I successfully installed mongoCXX. However, I am still facing some difficulties with the installation process, specifically with the [MongoDB (PEA, optional)](https://github.com/GeoscienceAustralia/ginan) step.

I have tried several approaches to overcome this issue, but I have not been able to make any significant progress so far. 

My wish is to have this software installed on WSL. Unfortunately, I still have the same error.

Best regards,

Waley.

**Comment by Waley04** [comment]
@JohnDonovanGA,

Yes, I am on WSL as you noted. I could not install the software on WSL despite my efforts. I suspect it is due to compatibility or dependency issues.

I managed the following:

**Mongo_cxx_driver (PEA):**
[Mongo_cxx_driver.log](https://github.com/GeoscienceAustralia/ginan/files/11468717/Mongo_cxx_driver.log)

**MongoDB (PEA, optional):**
![mongoDb](https://github.com/GeoscienceAustralia/ginan/assets/101952777/167ac0be-a2f8-478b-a407-ead98a845231)

I am still working on it and will keep you posted.

Thanks,

Waley.

**Comment by JohnDonovanGA** [comment]
Hi,
I have had a look at my WSL build. All the dependencies have been installed in /usr/local. This is also true of your mongo-cxx install from what I can see (in the log file attached). Can you please check you have libmongocxx.so and libbsoncxx.so in your /usr/local/lib directory? While your log looks OK it is not clear if these files were created. (They will probably be softlinks to other files in the same directory)
Thanks
John

**Comment by JohnDonovanGA** [comment]
Can you also give ,me a listing of what you find in /usr/local/lib/cmake (and if there, mongocxx-3.6.0 in that directory)

**Comment by Waley04** [comment]
@JohnDonovanGA,

Thank you for your unwavering passion to help. Check below and advise:

[user_local_lib_cmake.log](https://github.com/GeoscienceAustralia/ginan/files/11469774/user_local_lib_cmake.log)

Let me know if you need further information from my end.

Regards,

**Comment by Waley04** [comment]
> Hi, I have had a look at my WSL build. All the dependencies have been installed in /usr/local. This is also true of your mongo-cxx install from what I can see (in the log file attached). Can you please check you have libmongocxx.so and libbsoncxx.so in your /usr/local/lib directory? While your log looks OK it is not clear if these files were created. (They will probably be softlinks to other files in the same directory) Thanks John

@JohnDonovanGA,

Attached is a file containing the contents of the '**/usr/local/lib**' directory:

**Check this** **==>** <[user_local_lib.log](https://github.com/GeoscienceAustralia/ginan/files/11469810/user_local_lib.log)**>**

Looking forward to hearing from you soon.

Regards

**Comment by JohnDonovanGA** [comment]
Hi Waley, it looks like the install did not work properly as the files for mongocxx were not created.  I have attached tar.gz files from my machine that you can try to unpack and see if things work for you. libmongocxx.tar.gz is unpacked in /usr/local/lib, mongocxx-include.tar.gz is unpacked in /usr/local/include, and mongocxx-cmake.tar.gz in /usr/local/lib/cmake.
Let me know how you get on.
[libmongocxx.tar.gz](https://github.com/GeoscienceAustralia/ginan/files/11470980/libmongocxx.tar.gz)
[mongocxx-include.tar.gz](https://github.com/GeoscienceAustralia/ginan/files/11470976/mongocxx-include.tar.gz)
[mongocxx-cmake.tar.gz](https://github.com/GeoscienceAustralia/ginan/files/11470988/mongocxx-cmake.tar.gz)

**Comment by Waley04** [comment]
Hi @JohnDonovanGA ,

Thank you for the libraries and dependencies. I did as advised and I managed to install **POD** successfully. 

**For example:** 
![podWorksForMe](https://github.com/GeoscienceAustralia/ginan/assets/101952777/b47a1ae0-87c0-43a9-a0dd-f925e755c876)

However,  I am still having trouble with **PEA.** Please see the attached installation log for details. 

**PEA Installation Log**
[makePeaJ2.log](https://github.com/GeoscienceAustralia/ginan/files/11474013/makePeaJ2.log)

Your usual support would be appreciated.

Thank you.

**Comment by JohnDonovanGA** [comment]
Hi Waley, it looks like your version of the C++ compiler is not up to our specifications. Can you g++ --version and let me know what it says? You should be using gcc 9.4.0 or thereabouts.

**Comment by Waley04** [comment]
Hi John,

Here is what I have: 
![g++](https://github.com/GeoscienceAustralia/ginan/assets/101952777/15e81c73-af71-4d39-8b1d-1b802b11a39f)

Please, advise.

Thanks.

**Comment by JohnDonovanGA** [comment]
OK, but your log shows you are using C++ 11 std and you should be using at least c++ 2017 std. Let me get back to you on this one, the CXX args in the cmakefile should be specifying which std to be using.

**Comment by JohnDonovanGA** [comment]
Hi waley, we have done some research and find that if you make the switch to boost 1.74.0 you will get over the compilation hump. To do this you need to remove boost 1.73.0 from your system (ie remove all boost libs and includes from /usr/local and also the /usr/local/lib/cmake boost dir. Now install boost-1.74.0 (just use the instructions from installing 1.73.0). Lastly you need to modify the top level CMakeLists.txt file to specify boost 1.74.0 is required.
Let us know how you get on. It compiled for me, but I have not checked if it works on WSL yet or not. We also think you may need to install mongo-c-driver 1.21.2, mongocxx 3.7.0 as well but as yet I am having some difficulty with these as well on WSL.

**Comment by JohnDonovanGA** [comment]
Hi Duarte, the issue is likely to be an incompatability between mongo and SSL. We think it is fixed if you moved to Ubuntu 22.04. You may need to follow the steps advised to Waley though, please advise.

**Comment by Waley04** [comment]
> Hi waley, we have done some research and find that if you make the switch to boost 1.74.0 you will get over the compilation hump. To do this you need to remove boost 1.73.0 from your system (ie remove all boost libs and includes from /usr/local and also the /usr/local/lib/cmake boost dir. Now install boost-1.74.0 (just use the instructions from installing 1.73.0). Lastly you need to modify the top level CMakeLists.txt file to specify boost 1.74.0 is required. Let us know how you get on. It compiled for me, but I have not checked if it works on WSL yet or not. We also think you may need to install mongo-c-driver 1.21.2, mongocxx 3.7.0 as well but as yet I am having some difficulty with these as well on WSL.

Hi John,

I have diligently adhered to your guidance, and I am happy to share that the valuable tips you provided have proven useful. Consequently, I have accomplished the successful installation of the PEA software.

=== For example ===
![image](https://github.com/GeoscienceAustralia/ginan/assets/101952777/76e8bc9e-999c-4471-9ad4-20adc1f5c55a)

Thanks for your support. 

Regards,

Waley.

**Comment by JohnDonovanGA** [comment]
that's great news Waley. Good luck

**Comment by JohnDonovanGA** [comment]
No response from Duarte. Closing
