### ISSUE TITLE
wrong system char code for SBAS

### ISSUE THREAD

**Issue by thetengda** [GeoscienceAustralia/ginan#44]
in src/cpp/common/satSys.hpp line50 and line 64
system code for SBAS is set to lowercase 's'
however,  other functions (e.g. sysFromChar) use uppercase 'S'
This can lead to misrecognition

Code: 

#define SBAS_CHAR 's'
	/** Returns the character used as a prefix for this system.
	*/
	char sysChar()	const
	{
		switch (sys)
		{
			case E_Sys::GPS:	return 'G';
			case E_Sys::GLO:	return 'R';
			case E_Sys::GAL:	return 'E';
			case E_Sys::QZS:	return 'J';
			case E_Sys::BDS:	return 'C';
			case E_Sys::LEO:	return 'L';
			case E_Sys::IRN:	return 'I';
			case E_Sys::SBS:	return SBAS_CHAR;
			default:			return '-';
		}
	}

**Comment by seballgeyer** [comment]
Thanks for notifying us of this issue, we have fixed it in our development version. Changes will be pushed to GitHub in the coming weeks.
