### ISSUE TITLE
Real-time stream connect problem: wrong version number 

### ISSUE THREAD

**Issue by whu-dyf** [GeoscienceAustralia/ginan#47]
Dear Ginan Team,

I am writing to report some errors that I encountered while attempting to record streams using Ginan. Initially, I suspected that my stream configuration might be incorrect, but it works well with rtklib and BNC.

Furthermore, I tried to use curl to test the streams, as outlined in your documentation. While the command line in your example (as shown in Figure 2) worked well, my own stream configuration did not. I would greatly appreciate it if you could provide me with more information regarding the stream format. Specifically, I am unsure whether the port (such as: 2101) should be included in input stream format or not.

Thank you in advance for your assistance.
![1690462402739](https://github.com/GeoscienceAustralia/ginan/assets/31154686/16de9129-9291-4f36-acbb-31e9492d703d)
<img width="835" alt="image" src="https://github.com/GeoscienceAustralia/ginan/assets/31154686/acea87ac-a2cb-4d05-a960-6b9fb3e5fb11">
<img width="660" alt="image" src="https://github.com/GeoscienceAustralia/ginan/assets/31154686/ff9f8312-1aea-44ad-8b2d-a58d1a82b95a">

**Comment by whu-dyf** [comment]
Even if I run record_streams.yaml in the exampleConfigs, it still can not work. I just put my username and password in the <USER> and <PASS>.
![image](https://github.com/GeoscienceAustralia/ginan/assets/31154686/e7674449-0ffa-4256-8206-729872eda273)
![image](https://github.com/GeoscienceAustralia/ginan/assets/31154686/53954c36-7f20-44f6-8eb2-cbaf1c4bb2da)

**Comment by WhuGcLC** [comment]
Hello, I have the same questions as you.Could you tell me how to solve this problem?
