### ISSUE TITLE
Can Ginan support Ntrip 1.0?

### ISSUE THREAD

**Issue by whu-dyf** [GeoscienceAustralia/ginan#48]
NTRIP Version 1.0 is used for Hong Kong GNSS Raw Data Streams, So I want to ask whether Ginan real-time mode can support process ntrip 1.0 data.

**Comment by polytopes-design** [comment]
Hello,
Ginan does not currently support NTRIP Version 1. 
ntripSocket.cpp checks for a correct `HTTP/xxx 200` response which I believe is incompatible with NTRIPv1
We will investigate whether adding this capability is a simple change for a future release.

The relevant code segment is probably here
```
	if	( !response_stream 
		|| http_version.substr(0, 5) != "HTTP/"
		|| status_code != 200)
```
