### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by mattkingncl** [GeoscienceAustralia/ginan#7]
hi team
Just pulled teh git hub repository and installed (I think) all the dependencies on Ubuntu 20.

On make

[ 74%] Built target timesystem
[ 74%] Building CXX object CMakeFiles/pea.dir/cpp/common/ntripBroadcast.cpp.o
/opt/apps/ginan/src/cpp/common/ntripBroadcast.cpp:4:10: fatal error: bsoncxx/builder/basic/document.hpp: No such file or directory
    4 | #include <bsoncxx/builder/basic/document.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pea.dir/build.make:115: CMakeFiles/pea.dir/cpp/common/ntripBroadcast.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:874: CMakeFiles/pea.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

thoughts?
matt

**Comment by JohnDonovanGA** [comment]
no further feedback. closing issue
